program_firsts = ["int", "void", "$"]
declaration_list_firsts = ["int", "void", "$"]
declaration_firsts = ["int", "void"]
declaration_initial_firsts = ["int", "void"]
declaration_prime_firsts = [";", "[", "("]
var_declaration_prime_firsts = [";", "["]
fun_declaration_prime_firsts = ["("]
type_specifier_firsts = ["int", "void"]
params_firsts = ["int", "void"]
param_list_firsts = [",", "$"]
param_firsts = ["int", "void"]
param_prime_firsts = ["[", "$"]
compound_stmt_firsts = ["{"]
statement_list_firsts = ["ID", ";", "NUM", "(", "{", "break", "if", "for", "return", "+", "-", "$"]
statement_firsts = ["ID", ";", "NUM", "(", "{", "break", "if", "for", "return", "+", "-"]
expression_stmt_firsts = ["ID", ";", "NUM", "(", "break", "+", "-"]
selection_stmt_firsts = ["if"]
else_stmt_firsts = ["endif", "else"]
iteration_stmt_firsts = ["for"]
return_stmt_firsts = ["return"]
return_stmt_prime_firsts = ["ID", ";", "NUM", "(", "+", "-"]
expression_firsts = ["ID", "NUM", "(", "+", "-"]
b_firsts = ["[", "(", "=", "<", "==", "+", "-", "*", "$"]
h_firsts = ["=", "<", "==", "+", "-", "*", "$"]
simple_expression_zegond_firsts = ["NUM", "(", "+", "-"]
simple_expression_prime_firsts = ["(", "<", "==", "+", "-", "*", "$"]
c_firsts = ["<", "==", "$"]
relop_firsts = ["<", "=="]
additive_expression_firsts = ["ID", "NUM", "(", "+", "-"]
additive_expression_prime_firsts = [';', ']', '(', ')', ',', '<', '==', '+', '-', '*']
additive_expression_zegond_firsts = ["NUM", "(", "+", "-"]
d_firsts = ["+", "-", "$"]
addop_firsts = ["+", "-"]
term_firsts = ["ID", "NUM", "(", "+", "-"]
term_prime_firsts = [';', ']', '(', ')', ',', '<', '==', '+', '-', '*']
term_zegond_firsts = ["NUM", "(", "+", "-"]
g_firsts = [';', ']', ')', ',', '<', '==', '+', '-', '*']
signed_factor_firsts = ["ID", "NUM", "(", "+", "-"]
signed_factor_prime_firsts = [';', ']', '(', ')', ',', '<', '==', '+', '-', '*']
signed_factor_zegond_firsts = ["NUM", "(", "+", "-"]
factor_firsts = ["ID", "NUM", "("]
var_call_prime_firsts = ["[", "(", "$"]
var_prime_firsts = [';', '[', ']', ')', ',', '<', '==', '+', '-', '*']
factor_prime_firsts = [';', ']', '(', ')', ',', '<', '==', '+', '-', '*']
factor_zegond_firsts = ["NUM", "("]
args_firsts = ["ID", "NUM", "(", "+", "-", "$"]
arg_list_firsts = ["ID", "NUM", "(", "+", "-"]
arg_list_prime_firsts = [",", "$"]
